"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = QueueBar;
const jsx_runtime_1 = require("react/jsx-runtime");
const api_1 = require("../api");
const lucide_react_1 = require("lucide-react");
// Alttaki yatay skin sırası — "Patchle" butonu tüm kuyruğu tek seferde aktif eder
function QueueBar({ queue, activeIds, isPatching, patchProgress, onRemoveItem, onClear, onPatch, onStopPatches }) {
    return ((0, jsx_runtime_1.jsx)("div", { className: "shrink-0 border-t border-white/[0.08] bg-[#0c0c0e]/95 backdrop-blur-md", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-4 px-4 py-3", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-2 shrink-0 w-24", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.ListOrdered, { className: "w-5 h-5 text-sky-400", strokeWidth: 2 }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("p", { className: "text-xs font-bold tracking-wide text-sky-300", children: "SK\u0130N SIRASI" }), (0, jsx_runtime_1.jsxs)("p", { className: "text-[10px] text-gray-500", children: [queue.length, " skin"] })] })] }), (0, jsx_runtime_1.jsx)("div", { className: "flex-1 min-w-0 overflow-x-auto", children: queue.length === 0 ? ((0, jsx_runtime_1.jsxs)("p", { className: "text-gray-600 text-xs italic px-2 flex items-center gap-1", children: ["Skini modalden veya kart \u00FCzerindeki", ' ', (0, jsx_runtime_1.jsx)("span", { className: "inline-flex items-center justify-center text-blue-400 not-italic border border-blue-500/40 rounded px-1", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Plus, { className: "w-3 h-3", strokeWidth: 2.5 }) }), ' ', "butonu ile s\u0131raya ekleyin; tek t\u0131kla toplu patchleyin."] })) : ((0, jsx_runtime_1.jsx)("div", { className: "flex gap-2 pb-1", children: queue.map((meta) => {
                            const isActive = activeIds.has(meta.id);
                            return ((0, jsx_runtime_1.jsxs)("div", { className: `relative shrink-0 w-28 rounded-lg overflow-hidden border transition ${isActive ? 'border-green-500/60' : 'border-white/[0.1] hover:border-sky-500/50'}`, children: [(0, jsx_runtime_1.jsx)("div", { className: "aspect-video overflow-hidden bg-white/[0.03]", children: (0, jsx_runtime_1.jsx)("img", { src: (0, api_1.getSkinImageUrl)(meta.num, meta.championId), alt: meta.name, className: "w-full h-full object-cover", onError: (e) => {
                                                ;
                                                e.target.style.display = 'none';
                                            } }) }), (0, jsx_runtime_1.jsx)("p", { className: "text-[10px] text-gray-300 truncate px-1.5 py-0.5 bg-black/40", children: meta.name }), isActive && ((0, jsx_runtime_1.jsxs)("span", { className: "absolute top-1 left-1 flex items-center gap-0.5 bg-green-500/90 text-white text-[8px] font-bold px-1 py-px rounded", children: [(0, jsx_runtime_1.jsx)("span", { className: "w-1 h-1 bg-white rounded-full animate-pulse" }), "AKT\u0130F"] })), (0, jsx_runtime_1.jsx)("button", { onClick: () => onRemoveItem(meta.id), disabled: isPatching, title: "S\u0131radan \u00E7\u0131kar", className: "absolute top-0.5 right-0.5 w-4 h-4 flex items-center justify-center rounded-full bg-black/70 text-gray-300 hover:bg-red-500/80 hover:text-white transition disabled:opacity-40", children: (0, jsx_runtime_1.jsx)(lucide_react_1.X, { className: "w-2.5 h-2.5", strokeWidth: 2.5 }) })] }, meta.id));
                        }) })) }), (0, jsx_runtime_1.jsxs)("div", { className: "shrink-0 flex items-center gap-2", children: [queue.length > 0 && ((0, jsx_runtime_1.jsx)("button", { onClick: onClear, disabled: isPatching, className: "text-xs text-gray-400 hover:text-red-300 border border-white/[0.1] hover:border-red-500/40 rounded-lg px-3 py-2.5 transition disabled:opacity-40", children: "Temizle" })), activeIds.size > 0 && ((0, jsx_runtime_1.jsxs)("button", { onClick: onStopPatches, disabled: isPatching, className: "inline-flex items-center gap-1.5 text-xs text-gray-400 hover:text-amber-300 border border-white/[0.1] hover:border-amber-500/40 rounded-lg px-3 py-2.5 transition disabled:opacity-40", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Pause, { className: "w-3.5 h-3.5", strokeWidth: 2 }), " Durdur"] })), (0, jsx_runtime_1.jsx)("button", { onClick: onPatch, disabled: queue.length === 0 || isPatching, className: "bg-gradient-to-r from-blue-600 to-sky-500 hover:from-blue-500 hover:to-sky-400 px-6 py-2.5 rounded-xl font-bold text-sm transition shadow-lg shadow-sky-500/30 disabled:opacity-40 disabled:cursor-not-allowed flex items-center gap-2 whitespace-nowrap", children: isPatching ? ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)("span", { className: "animate-spin inline-block w-4 h-4 border-2 border-white border-t-transparent rounded-full" }), patchProgress || 'Patchleniyor...'] })) : ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Zap, { className: "w-4 h-4", strokeWidth: 2 }), " Patchle (", queue.length, ")"] })) })] })] }) }));
}
