"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = SkinModal;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_1 = require("react");
const api_1 = require("../api");
const lucide_react_1 = require("lucide-react");
const Spinner = () => ((0, jsx_runtime_1.jsx)("span", { className: "animate-spin inline-block w-4 h-4 border-2 border-white border-t-transparent rounded-full" }));
function extractColorName(fullName) {
    const match = fullName.match(/\(([^)]+)\)\s*$/);
    return match ? match[1] : fullName;
}
function SkinModal({ meta, isDownloaded, downloadProgress, isActive, isFavorite, inQueue, isApplying, isRemoving, onClose, onDownload, onApply, onDeactivate, onRemove, onToggleFavorite, onToggleQueue, chromas, loadingChromas, selectedChromaId, onSelectChroma }) {
    const isDownloading = downloadProgress !== undefined;
    const imageUrl = meta.previewDataUrl || (0, api_1.getSkinImageUrl)(meta.isCustom ? 0 : meta.num, meta.championId);
    const modalRef = (0, react_1.useRef)(null);
    const [modalHeight, setModalHeight] = (0, react_1.useState)();
    (0, react_1.useEffect)(() => {
        if (!modalRef.current)
            return;
        const el = modalRef.current;
        const observer = new ResizeObserver((entries) => {
            setModalHeight(entries[0].contentRect.height);
        });
        observer.observe(el);
        return () => observer.disconnect();
    }, []);
    return ((0, jsx_runtime_1.jsx)("div", { className: "fixed inset-0 bg-black/85 backdrop-blur-sm flex items-center justify-center z-50 p-4", onClick: () => {
            if (!isDownloading)
                onClose();
        }, children: (0, jsx_runtime_1.jsxs)("div", { className: "flex items-start gap-3", onClick: (e) => e.stopPropagation(), children: [(0, jsx_runtime_1.jsxs)("div", { ref: modalRef, className: "bg-[#18181b] border border-white/[0.1] rounded-2xl max-w-2xl w-full overflow-hidden shadow-2xl shadow-black/60 fade-in", children: [(0, jsx_runtime_1.jsxs)("div", { className: "relative aspect-video bg-black/50", children: [imageUrl ? ((0, jsx_runtime_1.jsx)("img", { src: imageUrl, alt: meta.name, className: "w-full h-full object-cover object-[center_20%]", onError: (e) => {
                                        ;
                                        e.target.style.display = 'none';
                                    } })) : ((0, jsx_runtime_1.jsx)("div", { className: "w-full h-full flex items-center justify-center text-gray-600", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Gamepad2, { className: "w-12 h-12", strokeWidth: 1.5 }) })), (0, jsx_runtime_1.jsx)("div", { className: "absolute inset-0 bg-gradient-to-t from-[#18181b] via-transparent to-transparent" }), (0, jsx_runtime_1.jsx)("button", { onClick: onClose, className: "absolute top-3 right-3 w-9 h-9 flex items-center justify-center rounded-full bg-black/60 backdrop-blur text-gray-300 hover:text-white hover:bg-black/80 transition", children: (0, jsx_runtime_1.jsx)(lucide_react_1.X, { className: "w-4 h-4", strokeWidth: 2 }) }), (0, jsx_runtime_1.jsx)("button", { onClick: onToggleFavorite, title: isFavorite ? 'Favorilerden çıkar' : 'Favorilere ekle', className: `absolute top-3 right-14 w-9 h-9 flex items-center justify-center rounded-full backdrop-blur transition ${isFavorite
                                        ? 'bg-sky-500 text-white shadow-lg shadow-sky-500/40'
                                        : 'bg-black/60 text-gray-300 hover:bg-sky-500/70 hover:text-white'}`, children: (0, jsx_runtime_1.jsx)(lucide_react_1.Heart, { className: "w-4 h-4", fill: isFavorite ? 'currentColor' : 'none', strokeWidth: 2 }) }), (0, jsx_runtime_1.jsxs)("div", { className: "absolute bottom-3 left-5 right-5 flex items-end justify-between gap-3", children: [(0, jsx_runtime_1.jsxs)("div", { className: "min-w-0", children: [(0, jsx_runtime_1.jsx)("h2", { className: "text-2xl font-bold tracking-tight truncate drop-shadow-lg", children: meta.name }), (0, jsx_runtime_1.jsxs)("p", { className: "text-gray-400 text-sm mt-0.5", children: [meta.championName && (0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [meta.championName, " \u00B7 "] }), meta.author && (0, jsx_runtime_1.jsxs)("span", { className: "text-purple-400 font-medium", children: ["Yap\u0131mc\u0131: ", meta.author, " \u00B7 "] }), "Skin ID: ", (0, jsx_runtime_1.jsx)("span", { className: "font-mono text-gray-300", children: meta.id })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "shrink-0 flex flex-col items-end gap-1.5", children: [meta.isCustom && ((0, jsx_runtime_1.jsx)("span", { className: "bg-purple-500/90 text-white text-xs font-bold px-3 py-1 rounded-full shadow-lg shadow-purple-500/30", children: "\u00D6ZEL" })), isActive && ((0, jsx_runtime_1.jsxs)("span", { className: "flex items-center gap-1.5 bg-green-500/90 text-white text-xs font-bold px-3 py-1 rounded-full shadow-lg shadow-green-500/30", children: [(0, jsx_runtime_1.jsx)("span", { className: "w-1.5 h-1.5 bg-white rounded-full animate-pulse" }), "AKT\u0130F"] })), !isActive && isDownloaded && ((0, jsx_runtime_1.jsxs)("span", { className: "flex items-center gap-1 bg-sky-600/90 text-white text-xs font-bold px-3 py-1 rounded-full shadow-lg shadow-sky-500/30", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Check, { className: "w-3.5 h-3.5", strokeWidth: 2.5 }), " \u0130ND\u0130R\u0130LD\u0130"] }))] })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "p-5", children: [isDownloading ? (
                                // İndirme ilerleme çubuğu
                                (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex justify-between items-center mb-2", children: [(0, jsx_runtime_1.jsxs)("span", { className: "text-sm text-gray-300 flex items-center gap-2", children: [(0, jsx_runtime_1.jsx)("span", { className: "animate-spin inline-block w-4 h-4 border-2 border-sky-500 border-t-transparent rounded-full" }), "\u0130ndiriliyor..."] }), (0, jsx_runtime_1.jsxs)("span", { className: "text-sm font-semibold text-sky-400", children: ["%", downloadProgress] })] }), (0, jsx_runtime_1.jsx)("div", { className: "w-full h-2.5 bg-white/[0.07] rounded-full overflow-hidden", children: (0, jsx_runtime_1.jsx)("div", { className: "h-full bg-gradient-to-r from-sky-500 to-blue-500 rounded-full transition-all duration-300", style: { width: `${downloadProgress}%` } }) })] })) : isDownloaded ? (
                                // İndirilmiş: Aktif Et / Pasifleştir + Sıra + Kaldır
                                (0, jsx_runtime_1.jsxs)("div", { className: "space-y-3", children: [isActive && ((0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-center gap-2 text-green-400 text-sm font-semibold bg-green-500/10 border border-green-500/30 rounded-xl py-2", children: [(0, jsx_runtime_1.jsx)("span", { className: "w-2 h-2 bg-green-400 rounded-full animate-pulse" }), "Patcher Aktif \u2014 bu skin oyunda uygulan\u0131yor"] })), (0, jsx_runtime_1.jsxs)("div", { className: "flex gap-3", children: [(0, jsx_runtime_1.jsx)("button", { onClick: onApply, disabled: isApplying, className: `flex-1 px-4 py-3 rounded-xl font-semibold transition shadow-lg flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed ${isActive
                                                        ? 'bg-white/[0.07] border border-green-500/40 text-green-300 hover:bg-green-500/10 shadow-green-500/10'
                                                        : 'bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-500 hover:to-emerald-500 shadow-green-500/20'}`, children: isApplying ? ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(Spinner, {}), "Aktif Ediliyor..."] })) : isActive ? ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Check, { className: "w-4 h-4", strokeWidth: 2.5 }), " Zaten Aktif"] })) : ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Check, { className: "w-4 h-4", strokeWidth: 2.5 }), " Aktif Et"] })) }), isActive ? ((0, jsx_runtime_1.jsxs)("button", { onClick: onDeactivate, disabled: isApplying, className: "px-5 py-3 rounded-xl font-semibold bg-amber-500/10 border border-amber-500/40 text-amber-300 hover:bg-amber-500/20 transition disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Square, { className: "w-3.5 h-3.5", fill: "currentColor", strokeWidth: 0 }), " Pasifle\u015Ftir"] })) : ((0, jsx_runtime_1.jsx)("button", { onClick: onToggleQueue, className: `px-5 py-3 rounded-xl font-semibold transition flex items-center justify-center gap-2 ${inQueue
                                                        ? 'bg-blue-500/20 border border-blue-500/50 text-blue-300 hover:bg-blue-500/30'
                                                        : 'bg-white/[0.06] border border-white/[0.1] hover:bg-blue-500/20 hover:border-blue-500/40 hover:text-blue-200'}`, children: inQueue ? ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Check, { className: "w-4 h-4", strokeWidth: 2.5 }), " S\u0131rada"] })) : ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Plus, { className: "w-4 h-4", strokeWidth: 2.5 }), " S\u0131raya Ekle"] })) })), (0, jsx_runtime_1.jsx)("button", { onClick: onRemove, disabled: isRemoving, className: "px-5 py-3 rounded-xl font-semibold bg-red-500/15 border border-red-500/40 text-red-300 hover:bg-red-500/25 transition disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2", children: isRemoving ? ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(Spinner, {}), "Kald\u0131r\u0131l\u0131yor..."] })) : ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Trash2, { className: "w-4 h-4", strokeWidth: 2 }), " Kald\u0131r"] })) })] })] })) : (
                                // Henüz indirilmemiş: SADECE indir (+ sıraya ekle seçeneği)
                                (0, jsx_runtime_1.jsxs)("div", { className: "space-y-3", children: [(0, jsx_runtime_1.jsxs)("button", { onClick: onDownload, className: "w-full bg-gradient-to-r from-sky-600 to-blue-600 hover:from-sky-500 hover:to-blue-500 px-4 py-3 rounded-xl font-semibold transition shadow-lg shadow-sky-500/25 flex items-center justify-center gap-2", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Download, { className: "w-4 h-4", strokeWidth: 2 }), " \u0130ndir"] }), (0, jsx_runtime_1.jsx)("button", { onClick: onToggleQueue, className: `w-full px-4 py-2.5 rounded-xl font-medium transition flex items-center justify-center gap-2 text-sm ${inQueue
                                                ? 'bg-blue-500/20 border border-blue-500/50 text-blue-300 hover:bg-blue-500/30'
                                                : 'bg-white/[0.05] border border-white/[0.1] text-gray-300 hover:bg-blue-500/15 hover:border-blue-500/40 hover:text-blue-200'}`, children: inQueue ? ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Check, { className: "w-4 h-4", strokeWidth: 2.5 }), " S\u0131rada \u2014 \u00E7\u0131karmak i\u00E7in t\u0131klay\u0131n"] })) : ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Plus, { className: "w-4 h-4", strokeWidth: 2.5 }), " S\u0131raya Ekle (sonra topluca patchleyin)"] })) })] })), (0, jsx_runtime_1.jsxs)("p", { className: "text-gray-600 text-xs mt-3 text-center inline-flex items-center gap-1 justify-center flex-wrap", children: ["Skin, LoLskins deposundan indirilir. Alt bardaki", ' ', (0, jsx_runtime_1.jsxs)("span", { className: "text-sky-400 font-semibold inline-flex items-center gap-1", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Zap, { className: "w-3 h-3", strokeWidth: 2.5 }), " Patchle"] }), ' ', "butonu ile s\u0131radaki t\u00FCm skinleri tek seferde aktif edebilirsiniz."] })] })] }), chromas.length > 0 && ((0, jsx_runtime_1.jsxs)("div", { className: "w-72 shrink-0 bg-[#18181b] border border-white/[0.1] rounded-2xl shadow-2xl shadow-black/60 p-3 overflow-y-auto", style: { maxHeight: modalHeight }, children: [(0, jsx_runtime_1.jsx)("p", { className: "text-xs font-bold text-gray-400 uppercase tracking-wide mb-2 px-1", children: "Chromalar" }), (0, jsx_runtime_1.jsxs)("div", { className: "grid grid-cols-2 gap-3", children: [(0, jsx_runtime_1.jsxs)("button", { onClick: () => onSelectChroma(null), className: `flex flex-col items-center gap-1.5 rounded-xl overflow-hidden border-2 transition p-2 ${selectedChromaId === null
                                        ? 'border-sky-400 bg-sky-500/10'
                                        : 'border-white/[0.1] bg-white/[0.02] hover:bg-white/[0.05]'}`, children: [(0, jsx_runtime_1.jsx)("div", { className: "aspect-[3/4] w-full rounded-lg bg-white/[0.06] flex items-center justify-center text-gray-400", children: (0, jsx_runtime_1.jsx)(lucide_react_1.RotateCcw, { className: "w-6 h-6", strokeWidth: 1.75 }) }), (0, jsx_runtime_1.jsx)("p", { className: "text-xs font-semibold text-gray-300", children: "Orijinal" })] }), chromas.map((chroma) => {
                                    const colorName = extractColorName(chroma.name);
                                    return ((0, jsx_runtime_1.jsxs)("button", { onClick: () => onSelectChroma(chroma.id), className: `flex flex-col items-center gap-1.5 rounded-xl overflow-hidden border-2 transition p-2 ${selectedChromaId === chroma.id
                                            ? 'border-sky-400 bg-sky-500/10'
                                            : 'border-white/[0.1] bg-white/[0.02] hover:bg-white/[0.05]'}`, children: [chroma.imageUrl ? ((0, jsx_runtime_1.jsx)("img", { src: chroma.imageUrl, alt: colorName, className: "aspect-[3/4] w-full rounded-lg object-cover bg-white/[0.06]", onError: (e) => {
                                                    ;
                                                    e.target.style.display = 'none';
                                                } })) : ((0, jsx_runtime_1.jsx)("div", { className: "aspect-[3/4] w-full rounded-lg", style: { background: chroma.colors?.[0] || '#333' } })), (0, jsx_runtime_1.jsx)("p", { className: "text-xs font-bold truncate w-full text-center text-white", children: colorName })] }, chroma.id));
                                })] }), loadingChromas && (0, jsx_runtime_1.jsx)("p", { className: "text-[11px] text-gray-500 mt-2 px-1", children: "Y\u00FCkleniyor..." })] }))] }) }));
}
