"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = SkinCard;
const jsx_runtime_1 = require("react/jsx-runtime");
const api_1 = require("../api");
const lucide_react_1 = require("lucide-react");
// Tüm grid'lerde (Şampiyonlar / Favoriler / İndirilenler) kullanılan ortak skin kartı
function SkinCard({ meta, isDownloaded, isActive, isFavorite, inQueue, isDownloading, isSelectable, isSelected, onSelect, onOpen, onToggleFavorite, onToggleQueue, onDownload }) {
    // Özel (custom) skinler için varsa önizleme görseli (previewDataUrl), 
    // yoksa şampiyonun varsayılan görselini (skin 0) gösteriyoruz.
    const imageUrl = meta.previewDataUrl || (0, api_1.getSkinImageUrl)(meta.isCustom ? 0 : meta.num, meta.championId);
    return ((0, jsx_runtime_1.jsx)("div", { onClick: isSelectable ? (e) => { e.stopPropagation(); onSelect(); } : onOpen, className: `group relative cursor-pointer transition-shadow duration-300 ${isSelectable ? 'cursor-pointer' : ''}`, children: (0, jsx_runtime_1.jsx)("div", { className: `relative bg-white/[0.03] border rounded-2xl overflow-hidden transition-all duration-300 hover:border-sky-400/60 hover:shadow-xl hover:shadow-sky-500/10 ${isActive ? 'border-green-500/50' : isSelectable && isSelected ? 'border-sky-500/50' : 'border-white/[0.06]'}`, children: (0, jsx_runtime_1.jsxs)("div", { className: "relative aspect-video bg-white/[0.03] overflow-hidden", children: [imageUrl ? ((0, jsx_runtime_1.jsx)("img", { src: imageUrl, alt: meta.name, className: "w-full h-full object-cover transition-transform duration-500 group-hover:scale-110", onError: (e) => {
                            e.target.style.display = 'none';
                        } })) : ((0, jsx_runtime_1.jsx)("div", { className: "w-full h-full flex items-center justify-center text-gray-600", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Gamepad2, { className: "w-8 h-8", strokeWidth: 1.5 }) })), (0, jsx_runtime_1.jsxs)("div", { className: "absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/85 via-black/30 to-transparent pt-10 pb-2 px-3 pointer-events-none rounded-b-2xl", children: [(0, jsx_runtime_1.jsx)("p", { className: "text-sm font-semibold text-white truncate", children: meta.name }), meta.championName && ((0, jsx_runtime_1.jsx)("p", { className: "text-[11px] text-gray-300 truncate", children: meta.championName }))] }), (0, jsx_runtime_1.jsx)("button", { onClick: (e) => {
                            e.stopPropagation();
                            onToggleFavorite();
                        }, title: isFavorite ? 'Favorilerden çıkar' : 'Favorilere ekle', className: `absolute top-2 left-2 w-8 h-8 rounded-full flex items-center justify-center backdrop-blur transition ${isFavorite
                            ? 'bg-sky-500/90 text-white shadow-lg shadow-sky-500/40'
                            : 'bg-black/50 text-gray-300 opacity-0 group-hover:opacity-100 hover:bg-sky-500/70'}`, children: (0, jsx_runtime_1.jsx)(lucide_react_1.Heart, { className: "w-4 h-4", fill: isFavorite ? 'currentColor' : 'none', strokeWidth: 2 }) }), isSelectable && ((0, jsx_runtime_1.jsx)("div", { className: "absolute bottom-2 right-2 z-10", children: (0, jsx_runtime_1.jsx)("div", { className: `w-6 h-6 rounded border-2 flex items-center justify-center transition ${isSelected
                                ? 'bg-sky-500 border-sky-500 text-white'
                                : 'bg-black/50 border-gray-400'}`, children: isSelected && (0, jsx_runtime_1.jsx)(lucide_react_1.Check, { className: "w-4 h-4", strokeWidth: 2.5 }) }) })), (0, jsx_runtime_1.jsxs)("div", { className: "absolute top-2 right-2 flex flex-col items-end gap-1 pointer-events-none", children: [meta.isCustom && ((0, jsx_runtime_1.jsx)("span", { className: "bg-purple-500/90 text-white text-[10px] font-bold px-2 py-0.5 rounded-full shadow-lg shadow-purple-500/30", children: "\u00D6ZEL" })), isDownloading && ((0, jsx_runtime_1.jsx)("span", { className: "bg-sky-600/90 text-white text-[10px] font-bold px-2 py-0.5 rounded-full shadow-lg shadow-sky-500/30 animate-pulse", children: "\u0130ND\u0130R\u0130L\u0130YOR..." })), !isDownloading && isActive && ((0, jsx_runtime_1.jsxs)("span", { className: "flex items-center gap-1 bg-green-500/90 text-white text-[10px] font-bold px-2 py-0.5 rounded-full shadow-lg shadow-green-500/30", children: [(0, jsx_runtime_1.jsx)("span", { className: "w-1.5 h-1.5 bg-white rounded-full animate-pulse" }), "AKT\u0130F"] })), !isDownloading && !isActive && isDownloaded && ((0, jsx_runtime_1.jsxs)("span", { className: "flex items-center gap-1 bg-sky-600/90 text-white text-[10px] font-bold px-2 py-0.5 rounded-full shadow-lg shadow-sky-500/30", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Check, { className: "w-3 h-3", strokeWidth: 2.5 }), " \u0130ND\u0130R\u0130LD\u0130"] }))] }), (0, jsx_runtime_1.jsxs)("div", { className: "absolute inset-x-0 bottom-0 flex justify-center gap-2 p-2 opacity-0 translate-y-2 group-hover:opacity-100 group-hover:translate-y-0 transition-all duration-200 bg-gradient-to-t from-black/85 via-black/40 to-transparent rounded-b-2xl", children: [!isDownloaded && !isDownloading && ((0, jsx_runtime_1.jsx)("button", { onClick: (e) => {
                                    e.stopPropagation();
                                    onDownload();
                                }, title: "\u0130ndir", className: "w-9 h-9 rounded-full bg-black/60 text-gray-200 flex items-center justify-center shadow-lg shadow-black/40 hover:bg-sky-600/90 hover:text-white hover:shadow-sky-500/30 transition", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Download, { className: "w-4 h-4", strokeWidth: 2 }) })), !isActive && ((0, jsx_runtime_1.jsx)("button", { onClick: (e) => {
                                    e.stopPropagation();
                                    onToggleQueue();
                                }, title: inQueue ? 'Sıradan çıkar' : 'Sıraya ekle', className: `w-9 h-9 rounded-full flex items-center justify-center shadow-lg transition ${inQueue
                                    ? 'bg-blue-500 text-white shadow-blue-500/40'
                                    : 'bg-black/60 text-gray-200 hover:bg-blue-600/80 hover:text-white shadow-black/40'}`, children: inQueue ? (0, jsx_runtime_1.jsx)(lucide_react_1.Check, { className: "w-4 h-4", strokeWidth: 2.5 }) : (0, jsx_runtime_1.jsx)(lucide_react_1.Plus, { className: "w-4 h-4", strokeWidth: 2.5 }) }))] })] }) }) }));
}
